Make variable matching non-greedy
shyras/osweb pull request #78
Opened 2017-07-20 17:31 UTC by smathot

Strings such as:

~~~
End of block [=var.count_block_sequence+1]<br /><br />Your average response time was [avg_rt] ms<br />Your accuracy was [acc] %<br /><br />Press any key to continue
~~~

Caused a crash because the regular expression to match `[]` expressions was greedy. I believe this small fix is sufficient.

However, I haven't been able to get the unit testing working, so please double check!

2017-07-20 19:36 UTC, dschreij commented
I will look at it as soon as I can. I do find it strange that you haven't managed to get the unit tests working though, as all the troublesome libraries and elements have been removed... Maybe reinstall the node_modules?

2017-07-22 03:57 UTC, dschreij commented
Alright, I see what you mean now, the regex as it was just matched everything between

`[=var.count ... acc]`

This seems like the proper solution. I'll see if I can add a test for this tomorrow and get back to you.

2017-07-22 21:58 UTC, dschreij commented
I ran the tests on your code, and now one test fails because of an *unterminated string constant*

~~~
Syntax
    parse_cmd()
      ✓ should parse command with arguments and keyword arguments
      ✓ should parse a single command with no arguments
      ✓ should parse command with escaped backslashes
      ✓ should ignore/not parse contents quoted keyword argument values
      ✓ should not parse contents of a (non-keyword arg) string value
      ✓ should be able to handle escaped backslashes
      ✓ should be able to handle escaped backslashes in keyword arguments
      ✓ should throw an exception when string can't be parsed
    eval_text()
      ✓ Should only parse real variables: \\[width] = \[width] = [width]
      ✓ Should not try to parse a variable if [] contents contain spaces: [no var]
      ✓ Should not try to parse a variable if [] contents contain non-alphanumeric (unicode) characters: [nóvar]
      ✓ Should parse variables with underscores and numbers: [my_var99]
      ✓ Should not try to parse a variable if it is preceded by a backslash: \[width]
      ✓ Should ignore characters between variable definitions: [width] x [height]
      ✓ Should process python code: [=10*10]
      ✓ Should not process python code if it is preceded by a backslash: \[=10*10]
      ✓ Should process string code: [="tést"]
      x Should process string code: [="\[test\]"]
    compile_cond()
      ✓ Should convert a variable within [] to a variable name within the var context
      ✓ Should handle >= correctly
      ✓ Should handle <= correctly
      ✓ Should convert always to True
      ✓ Should convert ALWAYS to True
      ✓ Should convert never to False
      ✓ Should convert NEVER to False
      ✓ Should quote literals at the end of the string
      ✓ Should convert a single = to double ==
      ✓ Should handle underscores in variable names
      ✓ Should handle lack of spaces surrounding = correctly
      ✓ Should not quote reserved words such as 'and' should also process double ==
      ✓ Should process a line starting with the = character as python script
      ✓ Should ignore existing quotes and add new quotes
      ✓ Should process backslashes in a proper way
      ✓ Should process more complex structures with brackets

  33 passing (455ms)
  1 failing

  1) Syntax eval_text() Should process string code: [="\[test\]"]:
     Error: Script parsing error: Unterminated string constant
      at Debugger.addError (src/js/osweb/system/debugger.js:49:15)
      at PythonParser._parse (src/js/osweb/python/python.js:76:40)
      at src/js/osweb/classes/syntax.js:129:56
      at String.replace (<anonymous>)
      at Syntax.eval_text (src/js/osweb/classes/syntax.js:121:27)
      at Context.<anonymous> (test/test.js:250:26)
~~~

I guess this is because it stops at the first ] it encounters; the regexp doesn't take into account that it is escaped. Escaped characters are really nasty to handle in JavaScript regexp, because it doesn't know a negative lookbehind.
I can't think of a quick fix for this problem at the moment and have to give it some more thought.

2017-07-22 22:01 UTC, dschreij requested changes
This fails in case of: [="\[test\]"]
~~~
  33 passing (455ms)
  1 failing

  1) Syntax eval_text() Should process string code: [="\[test\]"]:
     Error: Script parsing error: Unterminated string constant
~~~
see my comment on your PR for further details.

2017-07-22 22:07 UTC, dschreij commented
Speaking of greedy completion. Why does the test for
~~~
[width] x [height]
~~~
not fail without this change?

2017-07-24 08:01 UTC, merged

2017-07-24 08:24 UTC, smathot commented
@shyras The point of accepting changes is actually that you *don't* merge the pull request :wink: I'm working on the escaping issue (which is indeed not trivial).

2017-07-24 12:28 UTC, dschreij commented
Well, I think the problem(s) solved by your commit were more stringent than the escaping issue, so that somewhat justifies the merge, but it does still require some work 😉

Shall we add the statement that raises this issue to the tests as well?